### ISSUE TITLE
Member expression on number literal generates wrong output

### ISSUE THREAD

**Issue by Gozala** [estools/escodegen#104]
``` js
require("escodegen").generate({
            "type": "ExpressionStatement",
            "expression": {
                "type": "MemberExpression",
                "computed": false,
                "object": {
                    "type": "Literal",
                    "value": 4,
                    "raw": "4"
                },
                "property": {
                    "type": "Identifier",
                    "name": "foo"
                }
            }
        })
// => '4..foo;'
```

While it should output:

``` js
(4).foo;
```

**Comment by dannycochran** [comment]
@Constellation but why does it coerce it to 4..foo?

If you translate 4..foo back to an AST, the "raw" value of the Literal type is "4.", but the AST provided by @Gozala doesn't have that dot following the 4. It seems like the AST should actually be considered invalid, no?

**Comment by michaelficarra** [comment]
@dannycochran If the Literal AST node has a `raw` value (and it is lexically valid), it will be used. So the round-trip property still holds.

**Comment by dannycochran** [comment]
@michaelficarra but the AST changes roundtrip, no?

**Comment by michaelficarra** [comment]
Ah, I think I see what you mean. Thanks, @dannycochran. The fix here would be to compile to

```js
4 .foo;
```

**Comment by dannycochran** [comment]
@michaelficarra -- I think that seems right, though I could also see the case for escodegen to throw an error and say an AST like the one provided by @Gozala is invalid.

**Comment by michaelficarra** [comment]
@dannycochran I disagree. Those should be identical in an AST. The fact that they're not due to `raw` on Literal is the problem.
