### ISSUE TITLE
Cannot read property '0' of undefined error

### ISSUE THREAD

**Issue by KiPSOFT-zz** [estools/escodegen#190]
Hi i'm getting error "Cannot read property '0' of undefined error" this code;

var code = 'define(["jquery"], function($) {
   //this comment
}';

var ast = esprima.parse(code, {comment:true, range:true, tokens:true);
ast = escodegen.attachComments(ast, ast.comments, ast.tokens);
escodegen.generate(ast, {format: {escapeless: true}, comment:true});

how's solve this problem ?

thanks.

**Comment by yutingzhao1991** [comment]
I got the same problem, now you can use:

```js
  const ast = parseModule(content, {
    attachComment: true,
  });
```

not need `escodegen.attachComments` anymore.
