### ISSUE TITLE
Consider adding support for async/await

### ISSUE THREAD

**Issue by RReverser** [estools/escodegen#220]
I know these features are not approved and assumed to come only in ES7, but AST node structures for them seem to be already stabilized, so I'm wondering whether you consider adding support for those to escodegen at this point?

**Comment by Constellation** [comment]
Looks nice.
Do you know where is the spec? (Like BNF)

**Comment by RReverser** [comment]
@Constellation Not sure, I can look for it, but as for code generation - same rules as for `yield` work for `await`, too, and `async` is just a prefix before function itself. If you are ok with it, I can implement it.

**Comment by RReverser** [comment]
https://github.com/lukehoban/ecmascript-asyncawait - this is spec proposal.

**Comment by Constellation** [comment]
> If you are ok with it, I can implement it.

That's very very nice :)

> https://github.com/lukehoban/ecmascript-asyncawait - this is spec proposal.

Great!

**Comment by RReverser** [comment]
> That's very very nice :)

Since we all moved to single org, I'd better ask - do you want me to implement it in fork & send PR or just commit directly to the repo?

**Comment by Constellation** [comment]
> Since we all moved to single org, I'd better ask - do you want me to implement it in fork & send PR or just commit directly to the repo?

Either is fine to me :)

**Comment by michaelficarra** [comment]
Contributions should still go through the PR process, but they can be from a branch in this repo. We don't want to forego the review process just because we have an organisation.

**Comment by RReverser** [comment]
Oh... committed before saw your comment, @michaelficarra. Do you want me to revert / reset and send PR?

**Comment by RReverser** [comment]
I thought we now consider PRs for external contributors, and direct commits for org members so that we get faster fixes / improvements. Thoughts?

**Comment by inikulin** [comment]
@RReverser PR allows your ccolleagues review your code, which is always a great practice for any project, no matter which position you hold in it.

**Comment by RReverser** [comment]
@inikulin I agree it's pretty common practices among some teams, but there is also other type where colleagues just review ready commits - that's why I initially asked @Constellation about preferable way for our projects.

**Comment by michaelficarra** [comment]
I don't think we have to worry about open PRs sitting around forever given the visibility of these projects.

**Comment by Constellation** [comment]
@RReverser, @michaelficarra, @inikulin,

Personally either is fine to me. Sorry for troubling you.
If creating PR is considered major, I'll follow this direction :)

**Comment by RReverser** [comment]
Me too :)

**Comment by RReverser** [comment]
@Constellation Closing this issue. Could you please push an update to npm?

**Comment by Constellation** [comment]
> Could you please push an update to npm?

Yeah. I've published it as `1.6.0` :)
