### ISSUE TITLE
Unknown node type AssignmentPattern because estraverse is oudated

### ISSUE THREAD

**Issue by snowmantw** [estools/escodegen#229]
While estraverse already supported it, escodegen couldn't update the package (current in package.json is 1.9.1) without patch. I've tried to upgrade the package but escodegen would throw an error, as `TypeError: undefined is not a function`.

**Comment by pgilad** [comment]
Need to implement support for `AssignmentPattern`

**Comment by ianwjhalliday** [comment]
Howdy.  Is this planned to be merged in sometime soon?
