### ISSUE TITLE
generate() error has no message

### ISSUE THREAD

**Issue by drom** [estools/escodegen#250]
While calling `escodegen.generate()` it throws an error. `try - catch` is an empty object. How can I get a little more diagnostics or error messages?

**Comment by michaelficarra** [comment]
Are you sure? The only objects thrown by escodegen are instances of Error, which should have a `message` field. Try running `Object.getOwnPropertyNames` on it if you are currently using `Object.keys`; the fields are non-enumerable.

**Comment by drom** [comment]
Yes, you are right. The is a message. My mistake, I tried to `stringify()` an `Error` object and got an empty `{}`. The message was very short anyway. Something like: `Cannot read property 'type' of null` so I have to run `esvalid` in case of error in order to get more info. But it is good. Thank you for help.

**Comment by michaelficarra** [comment]
Be careful, esvalid hasn't been updated with support for any of the nodes introduced for ES6 support.

**Comment by drom** [comment]
woops. Are you serious? Not even `let`?

**Comment by michaelficarra** [comment]
Let uses the existing variable declaration node, so it should be fine. I would love to get a PR that adds ES6 support if someone wants to take it.

**Comment by drom** [comment]
We have some volunteers for adding ES6 support, if I understand the following issue correctly: https://github.com/estools/escodegen/issues/221

**Comment by michaelficarra** [comment]
No, I think #221 expresses a desire to change the implementation of escodegen to make use of ES6 features, not add support for generating programs from ES6 AST nodes.

**Comment by drom** [comment]
Does this sound relevant? https://github.com/estools/esvalid/issues/7

**Comment by michaelficarra** [comment]
Yes.
