### ISSUE TITLE
Release please? :)

### ISSUE THREAD

**Issue by ronkorving** [estools/escodegen#254]
With ES6 features becoming more and more common, I want my ES6 classes in io.js to start working :) Thanks in advance.

**Comment by tolmasky** [comment]
Yeah came here to ask the same thing, namely, is there any sort of timeline to expect? NPM lists the last release as 6 months ago. We're kind of in a weird situation now where escodegen has more or less fallen out of sync with all the other tools in this space (ast-types, acorn, etc). Totally understand if this is no longer a top priority of estools, but just want to know if we should start looking at alternatives.

**Comment by michaelficarra** [comment]
Published `1.7.0`: https://www.npmjs.com/package/escodegen

**Comment by ronkorving** [comment]
Thanks!
