### ISSUE TITLE
property translated to undefined after generate

### ISSUE THREAD

**Issue by klopfdreh** [estools/escodegen#279]
Hi,

first of all - thank you a lot for this cool JS Framework.

I've a little question regarding escodegen + nashorn - when I run the code you can see here:

https://github.com/klopfdreh/wicket/blob/5ca8af738b426b7947dea2d9ea7c305b299cb77a/wicket-core/src/main/java/org/apache/wicket/resource/NashornResource.js

and modify the AST - unshift an abort IfStatement into in a body of a loop e.g. WhileStatement the AST looks ok, but if I use generate the function invocation is going to be translated to undefined:

Actual output:
```javascript
x = 0;
while (x < 1) {
    if (nashornResourceReferenceScriptExecutionThread.undefined()) {
        print('NashornResource - Abort thread execution and skip all loop / function calls');
        break;
    }
    print('while' + x);
    x++;
}
```

Expected output:
```javascript
x = 0;
while (x < 1) {
    if (nashornResourceReferenceScriptExecutionThread.isInterrupted()) {
        print('NashornResource - Abort thread execution and skip all loop / function calls');
        break;
    }
    print('while' + x);
    x++;
}
```

Thanks in advance!

**Comment by michaelficarra** [comment]
The "property" field of MemberExpressions is an Expression, not a string.

**Comment by klopfdreh** [comment]
Thank you a lot! :+1:

**Comment by klopfdreh** [comment]
May I ask you how to modify it to fit my requirement?

**Comment by michaelficarra** [comment]
I think you want to use an `Identifier` node.

**Comment by klopfdreh** [comment]
That's working like a charm! Thanks!

**Comment by klopfdreh** [comment]
@michaelficarra - the reason why this happened was that the Oracle nashorn parser translated that into a MemberExpression what is wrong. I use esprima and everthing is working, now. Just wanted to mention that:

https://raw.githubusercontent.com/wicketstuff/core/574f223c7ec887846a160ad722c1ebf702ad7e10/nashorn-parent/nashorn/src/main/resources/org/wicketstuff/nashorn/resource/NashornResource.js
