### ISSUE TITLE
Wrong generation when using comment in function parameters

### ISSUE THREAD

**Issue by Alphapage** [estools/escodegen#283]
Hello,

When I want to regenerate this code:
```javascript
export default function imp(test// a comment
=[]
,test2 //comment 2
){}
```
I get this:
```javascript
export default function imp(test    // a comment
 undefined [], test2) {
}
```
Comments are not always generated and default value is corrupted.

Thanks in advance for your help.

**Comment by Alphapage** [comment]
I've tested my code using the latest version downloaded as a zip and I don't get any error.
But if I use require('escodegen') instead of require('./escodegen'), I get errors.

When will you publish or release this version to npm ?

**Comment by Alphapage** [comment]
I just needed too update package.json estraverse to 4.1.1 version and it seems to work perfectly

**Comment by michaelficarra** [comment]
Maybe you'd like to send a PR then?
