### ISSUE TITLE
Wrong output with hexadecimal escaped strings

### ISSUE THREAD

**Issue by sanex3339** [estools/escodegen#293]
problem: http://stackoverflow.com/questions/36357038/how-to-mangle-javascript-strings-using-hexadecimal-escape

Source code:
```
var a = 'a';
```

Mangled code:
```
var a = '\x61';
```

But after generation strings looks like:
```
var a = '\\x61';
```

How to fix that?

If i set `verbatim: 'raw'` - i get correct value but without quotes `var a = \x61`

More detail example:

```javascript
private obfuscate (asset: any, options: any) {
        let ast = esprima.parse(asset.source()); // var a = 'a';

        astUtils.traverse(ast, (node) => {
            if (node.type === 'Literal') {
                switch (typeof node.value) {
                    case 'string':
                        node.value = node.raw = this.stringToUnicode(node.value); // \x61

                        break;
                }
            }
        });

        let code = escodegen.generate(ast); // var a = '\\x61' instead of var a = '\x61'

        return new RawSource(code);
    }
```

**Comment by michaelficarra** [comment]
This is working properly. Your `stringToUnicode` function should not be generating escape sequences. Also, it does not make sense to set `.raw` and `.value` to the same string if it may contain an escape sequence.

**Comment by sanex3339** [comment]
I few not understand answer, maybe because not good understand of english, but i will very happy, if you show me right way.

For example, i simplify `stringToUnicode` function:

```javascript
private stringToUnicode (string: string): string {
       return '\u0061';
}
```

Which setting i must set? Or how i can change return value of function, to get correct result?
