### ISSUE TITLE
RegExps are rendered as [Object]

### ISSUE THREAD

**Issue by xpl** [estools/escodegen#294]
I use `escodegen` together with `esprima` (a fairly recent version from npm), and today I noticed that RegExps are not rendered correctly. After a brief investigation, I found that objects passed to the `generateRegExp` function do have unexpected structure, missing some fields and having new ones.

I temporarily solved the problem by replacing the old implementation with the following code. Seems that flags are now passed explicitly along with the expression object:

```javascript
    function generateRegExp(reg) {
            return '/' + reg.pattern + '/' + reg.flags;
    }
```

I also had to change it's invocation too (in `Literal` function):
```javascript
...
 return generateRegExp(expr.regex); // was expr.value before
```

I don't even know what I'm doing, so I would appreciate any help. Probably I'm doing it wrong.

**Comment by ciez** [comment]
I ran into the same issue: parsing valid js file with regexp and then regenerating it from AST displays [object Object]

as a work around, Identifier can be used to pass regex intact

**Comment by KnisterPeter** [comment]
Stumbled upon the same bug here paeckchen/paeckchen#239 using escodegen with acorn.
```
escodegen.generate(JSON.parse(JSON.stringify(acorn.parse('/a/g'))))
```

This will result in `[object Object]`

**Comment by KnisterPeter** [comment]
Could be closed then I think

**Comment by bobpearson** [comment]
I tried this on a project of mine, and it did fix the problem of re-serializing a regexp.  Thanks.

Will a new version with this fix be released in the near future?
