### ISSUE TITLE
Arrow function support

### ISSUE THREAD

**Issue by simondel** [estools/escodegen#303]
Are arrow functions supported and which version of Esprima is used in the online demo?

The [online demo](https://estools.github.io/escodegen/demo/index.html) states that the following code is invalid:

``` js
let multiply = (number) => { return number * 2 };
```

**Comment by nicojs** [comment]
Is there any update on this?

**Comment by artkoshelev** [comment]
Is there any update on this?

**Comment by simondel** [comment]
We're currently rewriting some modules to use Babel instead of escodegen in our project to work around this

**Comment by artkoshelev** [comment]
@simondel as far as i can see, Babel branch is merged, so would it resolve this issue?

**Comment by simondel** [comment]
We have decided to deprecate the code that was using escodegen and have written a new implementation that uses babylon and babel-generate
