### ISSUE TITLE
Issue with generating code for expressions with multiple unary operators

### ISSUE THREAD

**Issue by achoudhury85** [estools/escodegen#310]
Hello there

I ran into an issue where escodegen incorrectly generates code from the syntax tree for some generated asm.js.

Here's a repro for the problem:
    var chai = require('chai');
    var expect = chai.expect;
    var esprima = require('esprima');
    var escodegen = require('escodegen');

    describe('esprima tests', function() {
      it('esprima respects expressions with parentheses',
         function() {
           var src = 'n = +F(+(+(b | 0)));'; // <------------- The generated asm.js that is problematic.

           var parsedData = esprima.parse(src);
           process['stdout'].write(JSON.stringify(parsedData, null, 2));
           expect(escodegen.generate(parsedData)).to.equal(src);
         });
    })

OUTPUT: 
 1) esprima tests esprima respects expressions with parentheses:

      AssertionError: expected 'n = +F(+ +(b | 0));' to equal 'n = +F(+(+(b | 0)));'
      + expected - actual

      -n = +F(+ +(b | 0));
      +n = +F(+(+(b | 0)));

Hope this can be fixed :). Thanks in advance!

**Comment by michaelficarra** [comment]
Nope, this satisfies escodegen's contract: `parse(codegen(parse(js)))` is the same tree as `parse(js)`.

**Comment by angadgill92** [comment]
The ast generated for `-(-(10))` by esprima is the same as that generated for `- -(10)` but that doesn't mean that `- -(10)` is a valid expression. This is a valid issue.

**Comment by angadgill92** [comment]
Thanks. Just checked again. My bad!
