### ISSUE TITLE
'undefined' literal

### ISSUE THREAD

**Issue by arciisine** [estools/escodegen#318]
I'm looking through the code, and I am having trouble identifying a way in which I can use the 'undefined' literal.  I see support for 'null', but undefined is missing.  I'm not sure if this intentional, or just an oversight.  

A PR for this is pretty simple, and so if this is a bug, I am happy to open that.

**Comment by michaelficarra** [comment]
There's no such thing as an `undefined` literal in JavaScript. You can make a reference to the global variable named `undefined`.

**Comment by arciisine** [comment]
Thanks, that worked, treating it as an identifier.

**Comment by michaelficarra** [comment]
That's because it *is* an identifier.

**Comment by arciisine** [comment]
Correct, I was treating it incorrectly as a literal.
