### ISSUE TITLE
convert ast tree back to js code

### ISSUE THREAD

**Issue by djn3m0** [estools/escodegen#338]
Hello,
Im looking to do something exactly like this: https://estools.github.io/escodegen/demo/index.html. but from command line/linux terminal. 
Im getting AST tree in json format using acorn, is it possible to generate javascript code using escodegen?

Thanks

**Comment by davidbonnet** [comment]
You can use `esgenerate` (after having installed `escodegen` package):
```bash
acorn --ecma6 --module script.js > script.json
esgenerate script.json
```

Also, if you don't need all bells and whistles of Escodegen, you can pipe your JSON AST right through [Astring](https://github.com/davidbonnet/astring):
```bash
acorn --ecma6 --module script.js | astring --indent "  "
```
