### ISSUE TITLE
AssignmentPattern not available

### ISSUE THREAD

**Issue by XtremePlayzCODE** [estools/escodegen#341]
The node type `AssignmentPattern` is not allowed in escodegen, or atleast the online demo on esprima.org

**Comment by michaelficarra** [comment]
[Looks like it works to me](https://github.com/estools/escodegen/blob/719de3033c4a9a0df27f698c47b48d2af7241835/escodegen.js#L2212-L2214). Re-open with a repro case against `master` or ask esprima to update their online demo.
