### ISSUE TITLE
Function with try catch can not be generated without make an error.

### ISSUE THREAD

**Issue by SebastienAudier** [estools/escodegen#342]
exemple: 

function save() {
		try {
                     console.log("hello");
               } catch {
               }
}
source = esprima...
escodegen.generate(source);  
make an error

**Comment by michaelficarra** [comment]
You need a catch parameter.

**Comment by SebastienAudier** [comment]
Sorry for flooding, thank's

**Comment by SebastienAudier** [comment]
Sorry, but I tried with parameter. Sorry for bad example... And it doesn't work too. Any idea ?

function save() {
try {
console.log("hello");
} catch (e) {
}
}
source = esprima...
escodegen.generate(source);
make an error

**Comment by michaelficarra** [comment]
@SebastienAudier You're going to have to give a full repro if you want to get help with this. I can't assume what you are doing in the elided parts. Also use code blocks.

**Comment by SebastienAudier** [comment]
**the function:**

`function save() {
		try {
			source = codeMirror.getValue();
			if(selectedTab == "Functions") {
				if(selectedMethod == "constructor") {
					eval(selectedFunction + ' = ' + source);
					methodType = "constructor";
				} else {
					isCompiled = false;
					currentSources = anEsprima.body[0].body.body;
					for(var j=0; j < currentSources.length; j++) {
						esp = esprima.parse(source).body[0];
						if(esp.type == "FunctionDeclaration" && currentSources[j].type == "FunctionDeclaration") {
							if(currentSources[j].id.name == esp.id.name) {
								currentSources[j] = esprima.parse(source);
								eval(selectedFunction + ' = ' + escodegen.generate(anEsprima));
								isCompiled = true;
								methodType = "Function";
							}
						} 
						if(esp.type == "VariableDeclaration" && currentSources[j].type == "VariableDeclaration") {
							if(currentSources[j].declarations[0].id.name == esp.declarations[0].id.name) {	
								currentSources[j] = esprima.parse(source);
								eval(selectedFunction + ' = ' + escodegen.generate(anEsprima));
								isCompiled = true;
								methodType = "Variable";
							}
						}
						if(currentSources[j].type == "ExpressionStatement") {
							if((esp.expression.type == "AssignmentExpression") && (currentSources[j].expression.type == "AssignmentExpression")) {
								if(currentSources[j].expression.left.object.name == esp.expression.left.object.name) {	
									if(currentSources[j].expression.left.property.name == esp.expression.left.property.name) {	
										currentSources[j] = esprima.parse(source);
										eval(selectedFunction + ' = ' + escodegen.generate(anEsprima));
										isCompiled = true;
										methodType = "Expression";
									}
								}
							}
						}
					}
					if(!isCompiled) {
						esp = esprima.parse(source);
						if(esp.body[0].type == "FunctionDeclaration") {
							selectedMethod = esp.body[0].id.name;
							methodType = "Function";
						}
						if(esp.body[0].type == "VariableDeclaration") {
							selectedMethod = esp.body[0].declarations[0].id.name;
							methodType = "Variable";
						}
						if(esp.body[0].type == "ExpressionStatement") {
							selectedMethod = "anonymous expressions";
							methodType = "Expression";
						}
						// push just after selectedItem !!!
						currentSources.push(esp);
						eval(selectedFunction + ' = ' + escodegen.generate(anEsprima));
					}
				}
			}
			for (var i in this) {
				if(this[i]) {
					if(typeof this[i] == "function") {
						if(this[i].prototype) {
							if(this[i].prototype.constructor.name == selectedFunction) {
								functions[selectedFunction] = eval(selectedFunction + '.prototype');	
							}
						}
					}
				}
			}
			originalSource = source;		
			jQuery(".function-structure").remove();
			jQuery(".closure-structure").remove();
			jQuery(".content").remove();
			jQuery(".shortcut").remove();
			FunctionStructure().appendTo(jQuery("#js-browser"));
			Content(originalSource, anEsprima).appendTo(jQuery("#js-browser"));
			ShortcutTab().appendTo(jQuery("#js-browser"));
		} 
		catch(e) {
			console.log("error to compile: " + e.description);
		}
	}


// after 

var esp = esprima.parse(save.constructor.toString());
for(var j=0; j<esp.body[0].body.body.length; j++) {
			source = esp.body[0].body.body[j];	
                        escodegen.generate(source)
}`


**Error:**

Uncaught TypeError: Cannot read property 'length' of undefined
    at generateStatement (escodegen.browser.js:2010)
    at escodegen.browser.js:1843
    at withIndent (escodegen.browser.js:1019)
    at generateStatement (escodegen.browser.js:1841)
    at maybeBlock (escodegen.browser.js:1171)
    at generateFunctionBody (escodegen.browser.js:1230)
    at generateStatement (escodegen.browser.js:2200)
    at Object.generate (escodegen.browser.js:2350)
    at scanConstructor (jsBrowser.js:401)

The error append when escodegen try to generate source on save function (FunctionStatement with save Identifier)
