### ISSUE TITLE
Property issue in ObjectPattern

### ISSUE THREAD

**Issue by wisec** [estools/escodegen#358]
Hello I've stumbled in this code example:
```
let { test:myvar = "default" }= { test: "aValue" };
```
Escodegen outputs the following code from Esprima AST:
```
let {
    myvar = 'default': myvar = 'default'
} = { test: 'aValue' };
```
Which is obviously wrong.
Sample code to reproduce:
```
var es_parse = require('esprima').parse;
var esgenerate = require('escodegen').generate
var code = 'let { test:myvar = "default" }= { test: "aValue" };';
var ast = es_parse(code);
console.log(esgenerate(ast));
```

Thanks!

**Comment by wisec** [comment]
Any feedback?

**Comment by bsl-zcs** [comment]
I've hit this bug with fuse-box bundler which uses acorn parser.  

```
function a({b:c="d"}) { console.log(c) }
```
produced 
```
function a({
    c = 'd': c = 'd'
}) {
    console.log(c);
}
```
Your patch fixes it well, thanks!  Hope it will be merged and released soon.

**Comment by wisec** [comment]
@michaelficarra @Constellation any feedback would be welcome.
Asking this in a bit of a rush because we hope the PR to be approved and get it to mainstream.

Thanks
