### ISSUE TITLE
Dead Project?

### ISSUE THREAD

**Issue by wisec** [estools/escodegen#360]
Guys,
Escodegen is used a lot by the community, it would be very kind of you to clarify if this project is still maintained.

**Comment by michaelficarra** [comment]
Depends on what you mean by maintained.

**Comment by wisec** [comment]
@michaelficarra reply to issues and give some, even minimal, feedback on pull requests :)

**Comment by michaelficarra** [comment]
@wisec Sometimes things get lost when they're submitted during times that are really busy for other reasons. If nobody gets back to you, there's nothing wrong with sending a ping.

Btw, I had seen the last few PRs, they all looked good on initial glance, and they were on my list of GitHub things to get back to. Also, it would be super helpful if more people looked at PRs and gave reviews/approvals.

**Comment by wisec** [comment]
Thanks @michaelficarra :)

**Comment by wisec** [comment]
I'll try to do my best in giving back to the project by keeping it as much responsive as possible ;)
