### ISSUE TITLE
Incorrect code generation SequenceExpression in ForOf: for (let c of ('x', String('cat')) {}

### ISSUE THREAD

**Issue by johnjbarton** [estools/escodegen#371]
The RHS SequenceExpression is rendered without parenthesis.  

If you put 
```
for (let c of ('x', String('cat')) {}
```
into http://esprima.org/demo/rewrite.html, the rewrite fails.

https://github.com/estools/escodegen/blob/master/escodegen.js#L968 shows that the RHS 'of' has 
the `Precedence.Sequence`:
```
that.generateExpression(stmt.right, Precedence.Sequence, E_TTT)
```
But this is not correct, the std https://www.ecma-international.org/ecma-262/6.0/#sec-for-in-and-for-of-statements:
```
for ( LeftHandSideExpression of AssignmentExpression ) Statement
```
The lower precedence causes the parenthesize to fail:
```
    function parenthesize(text, current, should) {
        if (current < should) {
            return ['(', text, ')'];
        }
        return text;
    }
```

Simply changing the precedence fixes this issue.

**Comment by michaelficarra** [comment]
Fixed by #378.
