### ISSUE TITLE
Update license to BSD-2-Clause

### ISSUE THREAD

**Issue by sabgit** [estools/escodegen#390]
The license is currently set to BSD which is ambiguous. 
Can you please update to "BSD-2-Clause" (see https://spdx.org/licenses/BSD-2-Clause.html)

**Comment by brettz9** [comment]
Per https://github.com/estools/escodegen/blob/master/package.json#L52 , it is set to BSD-2-Clause and has been for quite some time. I'm guessing perhaps you were looking at the license for an older version.

I think this issue can be closed.

**Comment by U52284** [comment]
Can I ask what license it was before? The same just not enough specified?

**Comment by papandreou** [comment]
It's under version control, so you can find that in the git history: https://github.com/estools/escodegen/commit/02d47fee6e9822173d408123a9ea2583aa16cb38

**Comment by U52284** [comment]
Yes I saw that. but since before it was just BSD I dont know if the license was just better specified or it was changed. But then I will assume it was Clause 2 already before.

**Comment by papandreou** [comment]
Before it was pointing at [this url](https://raw.githubusercontent.com/estools/escodegen/master/LICENSE.BSD), which is also under version control: https://github.com/estools/escodegen/commits/master/LICENSE.BSD

So it has been the 2-clause version all along. The only change that has been made to it was [the addition of a copyright notice](https://github.com/estools/escodegen/commit/177ec89f93859c0873e67cb9fc5abacd9a421f83).

**Comment by U52284** [comment]
Alright perfect! Thank you.
