### ISSUE TITLE
Bug: Method on numbers are not wrapped: `(1.2).toString()` becomes `1.2..toString()`

### ISSUE THREAD

**Issue by GodaddyAntoGarand** [estools/escodegen#394]
The following code:
```javascript
(1.2).toString()
```
Should remain as-is, or be converted to `1.2.toString()`, but instead is converted to the following:
```javascript
1.2..toString();
```
Specifically, there is an extra period after the decimal number

Here is an AST representing this case:
```json
{
  "type": "ExpressionStatement",
  "expression": {
	"type": "CallExpression",
	"callee": {
	  "type": "MemberExpression",
	  "object": {
		"type": "Literal",
		"value": 1.2,
		"raw": "1.2"
	  },
	  "property": {
		"type": "Identifier",
		"name": "toString"
	  },
	  "computed": false
	},
	"arguments": []
  }
}
```
You can try it out on the [escodegen demo website](https://estools.github.io/escodegen/demo/index.html)

**Comment by papandreou** [comment]
`12..toString()` and `({}.toString());` are both valid JavaScript. Why did you expect a different output?

**Comment by GodaddyAntoGarand** [comment]
While they are valid javascript, the literal `12.` and `12` are slightly different when represented in AST form: The raw value of the Literal nodes are `12` and `12.`, somewhat as expected.
Demo: [ASTExplorer](https://astexplorer.net/#/gist/4d975cef6c02622acaeb1b9f2aa7d2c6/c52884b2b70f795afa8fab8be1a97162c8753686 gist).

It's pretty minor detail, but both are technically slightly different

**Comment by papandreou** [comment]
The `raw` and `extra` values attached to the nodes are just extra information about the lexical tokens of the original souce. They don't affect the semantics of the ast. I'm not the maintainer of this project, but I'm fairly sure that it's a non-goal to do a perfect round-trip.

**Comment by GodaddyAntoGarand** [comment]
Yea that would make sense, I didn't realise at first that it was the exact same AST 😄 

I did find a case where escodegen would generate invalid code though: 
If we use `(1.2).toString()` instead of `12`, the generated code is `1.2..toString();`, which is invalid javascript

I'll update the main post with details regarding this issue instead

**Comment by papandreou** [comment]
Hmm, weird! I cannot reproduce that?

```js
> require('escodegen').generate(require('acorn').parse('(1.2).toString()'))
'1.2.toString();'
```

(with `escodegen@1.11.1`)

**Comment by GodaddyAntoGarand** [comment]
Yea, I was trying it out on the demo website, which is still on version `0.0.16-dev` for some reason

It does work as expected on the adequate version, my bad!
