### ISSUE TITLE
word-wrap vulnerable to Regular Expression Denial of Service

### ISSUE THREAD

**Issue by nbouvrette** [estools/escodegen#459]
optionator  0.8.3 - 0.9.1 depends on a vulnerable version of `word-wrap`

The `word-wrap` package is vulnerable to Regular Expression Denial of Service.

Details here: https://github.com/advisories/GHSA-j8xg-fqg3-53r7

Please update to opionator to version 0.9.3 to fix this issue.

Dependency tree:

          └─┬ escodegen@1.14.3
            └─┬ optionator@0.8.3
              └── word-wrap@1.2.3

**Comment by Adhikaripr** [comment]
will we be getting any update on this?

**Comment by nbouvrette** [comment]
@michaelficarra is there any way you can help with this?

I think there is already a PR ready as well https://github.com/estools/escodegen/pull/457

**Comment by michaelficarra** [comment]
Duplicate of #458. You can upgrade to the latest version of escodegen to resolve this issue.

**Comment by nbouvrette** [comment]
My bad @michaelficarra I didn't realize optionator was removed in this [commit](https://github.com/estools/escodegen/commit/0b1a75b0ede550414b6b69faeb91add42325f244#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
